package com.gm.gmreader.dao;

import com.gm.gmreader.model.Accesslog;
import com.gm.gmreader.model.AccesslogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AccesslogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    long countByExample(AccesslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int deleteByExample(AccesslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int insert(Accesslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int insertSelective(Accesslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    List<Accesslog> selectByExample(AccesslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    Accesslog selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") Accesslog record, @Param("example") AccesslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int updateByExample(@Param("record") Accesslog record, @Param("example") AccesslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int updateByPrimaryKeySelective(Accesslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int updateByPrimaryKey(Accesslog record);
}