package com.gm.gmreader.dao;

import com.gm.gmreader.model.Branchchaptervo;
import com.gm.gmreader.model.BranchchaptervoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BranchchaptervoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branchchaptervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(BranchchaptervoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branchchaptervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(BranchchaptervoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branchchaptervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Branchchaptervo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branchchaptervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Branchchaptervo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branchchaptervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Branchchaptervo> selectByExample(BranchchaptervoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branchchaptervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Branchchaptervo record, @Param("example") BranchchaptervoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branchchaptervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Branchchaptervo record, @Param("example") BranchchaptervoExample example);
}