package com.gm.gmreader.dao;

import com.gm.gmreader.model.Branch;
import com.gm.gmreader.model.BranchExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Branch> selectByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    Branch selectByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Branch record, @Param("example") BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Branch record, @Param("example") BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByPrimaryKeySelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByPrimaryKey(Branch record);
}