package com.gm.gmreader.dao;

import com.gm.gmreader.model.Btoc;
import com.gm.gmreader.model.BtocExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BtocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(BtocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(BtocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByPrimaryKey(Integer bcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Btoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Btoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Btoc> selectByExample(BtocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    Btoc selectByPrimaryKey(Integer bcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Btoc record, @Param("example") BtocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Btoc record, @Param("example") BtocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByPrimaryKeySelective(Btoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByPrimaryKey(Btoc record);
}