package com.gm.gmreader.dao;

import com.gm.gmreader.model.Chat;
import com.gm.gmreader.model.ChatExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    long countByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int deleteByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int deleteByPrimaryKey(Integer chid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int insert(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int insertSelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    List<Chat> selectByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    Chat selectByPrimaryKey(Integer chid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") Chat record, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int updateByExample(@Param("record") Chat record, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int updateByPrimaryKeySelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int updateByPrimaryKey(Chat record);
}