package com.gm.gmreader.dao;

import com.gm.gmreader.model.Chatvo;
import com.gm.gmreader.model.ChatvoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChatvoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    long countByExample(ChatvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int deleteByExample(ChatvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int insert(Chatvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int insertSelective(Chatvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    List<Chatvo> selectByExample(ChatvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") Chatvo record, @Param("example") ChatvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    int updateByExample(@Param("record") Chatvo record, @Param("example") ChatvoExample example);
}