package com.gm.gmreader.dao;

import com.gm.gmreader.model.Discussvo;
import com.gm.gmreader.model.DiscussvoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DiscussvoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discussvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(DiscussvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discussvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(DiscussvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discussvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Discussvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discussvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Discussvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discussvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Discussvo> selectByExample(DiscussvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discussvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Discussvo record, @Param("example") DiscussvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discussvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Discussvo record, @Param("example") DiscussvoExample example);
}