package com.gm.gmreader.dao;

import com.gm.gmreader.model.Loginlog;
import com.gm.gmreader.model.LoginlogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LoginlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    long countByExample(LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int deleteByExample(LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int insert(Loginlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int insertSelective(Loginlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    List<Loginlog> selectByExample(LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    Loginlog selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") Loginlog record, @Param("example") LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int updateByExample(@Param("record") Loginlog record, @Param("example") LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int updateByPrimaryKeySelective(Loginlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    int updateByPrimaryKey(Loginlog record);
}