package com.gm.gmreader.dao;

import com.gm.gmreader.model.Readervo;
import com.gm.gmreader.model.ReadervoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReadervoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(ReadervoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(ReadervoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Readervo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Readervo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Readervo> selectByExample(ReadervoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Readervo record, @Param("example") ReadervoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readervo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Readervo record, @Param("example") ReadervoExample example);
}