package com.gm.gmreader.dao;

import com.gm.gmreader.model.Rtob;
import com.gm.gmreader.model.RtobExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RtobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(RtobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(RtobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByPrimaryKey(Integer rbid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Rtob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Rtob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Rtob> selectByExample(RtobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    Rtob selectByPrimaryKey(Integer rbid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Rtob record, @Param("example") RtobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Rtob record, @Param("example") RtobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByPrimaryKeySelective(Rtob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rtob
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByPrimaryKey(Rtob record);
}