package com.gm.gmreader.dao;

import com.gm.gmreader.model.Star;
import com.gm.gmreader.model.StarExample;
import com.gm.gmreader.model.StarKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByPrimaryKey(StarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Star> selectByExample(StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    Star selectByPrimaryKey(StarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Star record, @Param("example") StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Star record, @Param("example") StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByPrimaryKeySelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByPrimaryKey(Star record);
}