package com.gm.gmreader.dao;

import com.gm.gmreader.model.Starvo;
import com.gm.gmreader.model.StarvoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StarvoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(StarvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(StarvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Starvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Starvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Starvo> selectByExample(StarvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Starvo record, @Param("example") StarvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table starvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Starvo record, @Param("example") StarvoExample example);
}