package com.gm.gmreader.dao;

import com.gm.gmreader.model.Thumbvo;
import com.gm.gmreader.model.ThumbvoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThumbvoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumbvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    long countByExample(ThumbvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumbvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int deleteByExample(ThumbvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumbvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insert(Thumbvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumbvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int insertSelective(Thumbvo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumbvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    List<Thumbvo> selectByExample(ThumbvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumbvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Thumbvo record, @Param("example") ThumbvoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumbvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    int updateByExample(@Param("record") Thumbvo record, @Param("example") ThumbvoExample example);
}