package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Accesslog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.aid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.ip
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.url
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.method
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.status
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.sttime
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private Date sttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.endtime
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.query
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String query;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesslog.body
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.aid
     *
     * @return the value of accesslog.aid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.aid
     *
     * @param aid the value for accesslog.aid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.ip
     *
     * @return the value of accesslog.ip
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.ip
     *
     * @param ip the value for accesslog.ip
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.url
     *
     * @return the value of accesslog.url
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.url
     *
     * @param url the value for accesslog.url
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.method
     *
     * @return the value of accesslog.method
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.method
     *
     * @param method the value for accesslog.method
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.status
     *
     * @return the value of accesslog.status
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.status
     *
     * @param status the value for accesslog.status
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.sttime
     *
     * @return the value of accesslog.sttime
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public Date getSttime() {
        return sttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.sttime
     *
     * @param sttime the value for accesslog.sttime
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setSttime(Date sttime) {
        this.sttime = sttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.endtime
     *
     * @return the value of accesslog.endtime
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.endtime
     *
     * @param endtime the value for accesslog.endtime
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.query
     *
     * @return the value of accesslog.query
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.query
     *
     * @param query the value for accesslog.query
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setQuery(String query) {
        this.query = query == null ? null : query.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesslog.body
     *
     * @return the value of accesslog.body
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesslog.body
     *
     * @param body the value for accesslog.body
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesslog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", ip=").append(ip);
        sb.append(", url=").append(url);
        sb.append(", method=").append(method);
        sb.append(", status=").append(status);
        sb.append(", sttime=").append(sttime);
        sb.append(", endtime=").append(endtime);
        sb.append(", query=").append(query);
        sb.append(", body=").append(body);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}