package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Branch implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Date btime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bintro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bhimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.bpre
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer bpre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.bid
     *
     * @return the value of branch.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.bid
     *
     * @param bid the value for branch.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.bname
     *
     * @return the value of branch.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.bname
     *
     * @param bname the value for branch.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.btime
     *
     * @return the value of branch.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Date getBtime() {
        return btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.btime
     *
     * @param btime the value for branch.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBtime(Date btime) {
        this.btime = btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.bintro
     *
     * @return the value of branch.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBintro() {
        return bintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.bintro
     *
     * @param bintro the value for branch.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBintro(String bintro) {
        this.bintro = bintro == null ? null : bintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.bhimg
     *
     * @return the value of branch.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBhimg() {
        return bhimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.bhimg
     *
     * @param bhimg the value for branch.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBhimg(String bhimg) {
        this.bhimg = bhimg == null ? null : bhimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.bpre
     *
     * @return the value of branch.bpre
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getBpre() {
        return bpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.bpre
     *
     * @param bpre the value for branch.bpre
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBpre(Integer bpre) {
        this.bpre = bpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bid=").append(bid);
        sb.append(", bname=").append(bname);
        sb.append(", btime=").append(btime);
        sb.append(", bintro=").append(bintro);
        sb.append(", bhimg=").append(bhimg);
        sb.append(", bpre=").append(bpre);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}