package com.gm.gmreader.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BranchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public BranchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBidIsNull() {
            addCriterion("bid is null");
            return (Criteria) this;
        }

        public Criteria andBidIsNotNull() {
            addCriterion("bid is not null");
            return (Criteria) this;
        }

        public Criteria andBidEqualTo(Integer value) {
            addCriterion("bid =", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidNotEqualTo(Integer value) {
            addCriterion("bid <>", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidGreaterThan(Integer value) {
            addCriterion("bid >", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bid >=", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidLessThan(Integer value) {
            addCriterion("bid <", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidLessThanOrEqualTo(Integer value) {
            addCriterion("bid <=", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidIn(List<Integer> values) {
            addCriterion("bid in", values, "bid");
            return (Criteria) this;
        }

        public Criteria andBidNotIn(List<Integer> values) {
            addCriterion("bid not in", values, "bid");
            return (Criteria) this;
        }

        public Criteria andBidBetween(Integer value1, Integer value2) {
            addCriterion("bid between", value1, value2, "bid");
            return (Criteria) this;
        }

        public Criteria andBidNotBetween(Integer value1, Integer value2) {
            addCriterion("bid not between", value1, value2, "bid");
            return (Criteria) this;
        }

        public Criteria andBnameIsNull() {
            addCriterion("bname is null");
            return (Criteria) this;
        }

        public Criteria andBnameIsNotNull() {
            addCriterion("bname is not null");
            return (Criteria) this;
        }

        public Criteria andBnameEqualTo(String value) {
            addCriterion("bname =", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameNotEqualTo(String value) {
            addCriterion("bname <>", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameGreaterThan(String value) {
            addCriterion("bname >", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameGreaterThanOrEqualTo(String value) {
            addCriterion("bname >=", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameLessThan(String value) {
            addCriterion("bname <", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameLessThanOrEqualTo(String value) {
            addCriterion("bname <=", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameLike(String value) {
            addCriterion("bname like", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameNotLike(String value) {
            addCriterion("bname not like", value, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameIn(List<String> values) {
            addCriterion("bname in", values, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameNotIn(List<String> values) {
            addCriterion("bname not in", values, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameBetween(String value1, String value2) {
            addCriterion("bname between", value1, value2, "bname");
            return (Criteria) this;
        }

        public Criteria andBnameNotBetween(String value1, String value2) {
            addCriterion("bname not between", value1, value2, "bname");
            return (Criteria) this;
        }

        public Criteria andBtimeIsNull() {
            addCriterion("btime is null");
            return (Criteria) this;
        }

        public Criteria andBtimeIsNotNull() {
            addCriterion("btime is not null");
            return (Criteria) this;
        }

        public Criteria andBtimeEqualTo(Date value) {
            addCriterion("btime =", value, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeNotEqualTo(Date value) {
            addCriterion("btime <>", value, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeGreaterThan(Date value) {
            addCriterion("btime >", value, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("btime >=", value, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeLessThan(Date value) {
            addCriterion("btime <", value, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeLessThanOrEqualTo(Date value) {
            addCriterion("btime <=", value, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeIn(List<Date> values) {
            addCriterion("btime in", values, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeNotIn(List<Date> values) {
            addCriterion("btime not in", values, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeBetween(Date value1, Date value2) {
            addCriterion("btime between", value1, value2, "btime");
            return (Criteria) this;
        }

        public Criteria andBtimeNotBetween(Date value1, Date value2) {
            addCriterion("btime not between", value1, value2, "btime");
            return (Criteria) this;
        }

        public Criteria andBintroIsNull() {
            addCriterion("bintro is null");
            return (Criteria) this;
        }

        public Criteria andBintroIsNotNull() {
            addCriterion("bintro is not null");
            return (Criteria) this;
        }

        public Criteria andBintroEqualTo(String value) {
            addCriterion("bintro =", value, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroNotEqualTo(String value) {
            addCriterion("bintro <>", value, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroGreaterThan(String value) {
            addCriterion("bintro >", value, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroGreaterThanOrEqualTo(String value) {
            addCriterion("bintro >=", value, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroLessThan(String value) {
            addCriterion("bintro <", value, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroLessThanOrEqualTo(String value) {
            addCriterion("bintro <=", value, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroLike(String value) {
            addCriterion("bintro like", value, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroNotLike(String value) {
            addCriterion("bintro not like", value, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroIn(List<String> values) {
            addCriterion("bintro in", values, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroNotIn(List<String> values) {
            addCriterion("bintro not in", values, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroBetween(String value1, String value2) {
            addCriterion("bintro between", value1, value2, "bintro");
            return (Criteria) this;
        }

        public Criteria andBintroNotBetween(String value1, String value2) {
            addCriterion("bintro not between", value1, value2, "bintro");
            return (Criteria) this;
        }

        public Criteria andBhimgIsNull() {
            addCriterion("bhimg is null");
            return (Criteria) this;
        }

        public Criteria andBhimgIsNotNull() {
            addCriterion("bhimg is not null");
            return (Criteria) this;
        }

        public Criteria andBhimgEqualTo(String value) {
            addCriterion("bhimg =", value, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgNotEqualTo(String value) {
            addCriterion("bhimg <>", value, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgGreaterThan(String value) {
            addCriterion("bhimg >", value, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgGreaterThanOrEqualTo(String value) {
            addCriterion("bhimg >=", value, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgLessThan(String value) {
            addCriterion("bhimg <", value, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgLessThanOrEqualTo(String value) {
            addCriterion("bhimg <=", value, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgLike(String value) {
            addCriterion("bhimg like", value, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgNotLike(String value) {
            addCriterion("bhimg not like", value, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgIn(List<String> values) {
            addCriterion("bhimg in", values, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgNotIn(List<String> values) {
            addCriterion("bhimg not in", values, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgBetween(String value1, String value2) {
            addCriterion("bhimg between", value1, value2, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBhimgNotBetween(String value1, String value2) {
            addCriterion("bhimg not between", value1, value2, "bhimg");
            return (Criteria) this;
        }

        public Criteria andBpreIsNull() {
            addCriterion("bpre is null");
            return (Criteria) this;
        }

        public Criteria andBpreIsNotNull() {
            addCriterion("bpre is not null");
            return (Criteria) this;
        }

        public Criteria andBpreEqualTo(Integer value) {
            addCriterion("bpre =", value, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreNotEqualTo(Integer value) {
            addCriterion("bpre <>", value, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreGreaterThan(Integer value) {
            addCriterion("bpre >", value, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreGreaterThanOrEqualTo(Integer value) {
            addCriterion("bpre >=", value, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreLessThan(Integer value) {
            addCriterion("bpre <", value, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreLessThanOrEqualTo(Integer value) {
            addCriterion("bpre <=", value, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreIn(List<Integer> values) {
            addCriterion("bpre in", values, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreNotIn(List<Integer> values) {
            addCriterion("bpre not in", values, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreBetween(Integer value1, Integer value2) {
            addCriterion("bpre between", value1, value2, "bpre");
            return (Criteria) this;
        }

        public Criteria andBpreNotBetween(Integer value1, Integer value2) {
            addCriterion("bpre not between", value1, value2, "bpre");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table branch
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 08 17:05:12 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table branch
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}