package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Branchvo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.authorname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String authorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.authorid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer authorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Date btime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bintro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bhimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.bpre
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer bpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.num
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Long num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.up
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Long up;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branchvo.down
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Long down;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branchvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.bid
     *
     * @return the value of branchvo.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.bid
     *
     * @param bid the value for branchvo.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.bname
     *
     * @return the value of branchvo.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.bname
     *
     * @param bname the value for branchvo.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.authorname
     *
     * @return the value of branchvo.authorname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getAuthorname() {
        return authorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.authorname
     *
     * @param authorname the value for branchvo.authorname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setAuthorname(String authorname) {
        this.authorname = authorname == null ? null : authorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.authorid
     *
     * @return the value of branchvo.authorid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.authorid
     *
     * @param authorid the value for branchvo.authorid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.btime
     *
     * @return the value of branchvo.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Date getBtime() {
        return btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.btime
     *
     * @param btime the value for branchvo.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBtime(Date btime) {
        this.btime = btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.bintro
     *
     * @return the value of branchvo.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBintro() {
        return bintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.bintro
     *
     * @param bintro the value for branchvo.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBintro(String bintro) {
        this.bintro = bintro == null ? null : bintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.bhimg
     *
     * @return the value of branchvo.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBhimg() {
        return bhimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.bhimg
     *
     * @param bhimg the value for branchvo.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBhimg(String bhimg) {
        this.bhimg = bhimg == null ? null : bhimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.bpre
     *
     * @return the value of branchvo.bpre
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getBpre() {
        return bpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.bpre
     *
     * @param bpre the value for branchvo.bpre
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBpre(Integer bpre) {
        this.bpre = bpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.num
     *
     * @return the value of branchvo.num
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.num
     *
     * @param num the value for branchvo.num
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.up
     *
     * @return the value of branchvo.up
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Long getUp() {
        return up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.up
     *
     * @param up the value for branchvo.up
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setUp(Long up) {
        this.up = up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branchvo.down
     *
     * @return the value of branchvo.down
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Long getDown() {
        return down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branchvo.down
     *
     * @param down the value for branchvo.down
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setDown(Long down) {
        this.down = down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branchvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bid=").append(bid);
        sb.append(", bname=").append(bname);
        sb.append(", authorname=").append(authorname);
        sb.append(", authorid=").append(authorid);
        sb.append(", btime=").append(btime);
        sb.append(", bintro=").append(bintro);
        sb.append(", bhimg=").append(bhimg);
        sb.append(", bpre=").append(bpre);
        sb.append(", num=").append(num);
        sb.append(", up=").append(up);
        sb.append(", down=").append(down);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}