package com.gm.gmreader.model;

import java.io.Serializable;

public class Btoc implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btoc.bcid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer bcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btoc.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btoc.cid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btoc.bcid
     *
     * @return the value of btoc.bcid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getBcid() {
        return bcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btoc.bcid
     *
     * @param bcid the value for btoc.bcid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBcid(Integer bcid) {
        this.bcid = bcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btoc.bid
     *
     * @return the value of btoc.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btoc.bid
     *
     * @param bid the value for btoc.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btoc.cid
     *
     * @return the value of btoc.cid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btoc.cid
     *
     * @param cid the value for btoc.cid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btoc
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bcid=").append(bcid);
        sb.append(", bid=").append(bid);
        sb.append(", cid=").append(cid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}