package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Chapter implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.cid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.ctitle
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String ctitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.cbody
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String cbody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.ctime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chapter
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.cid
     *
     * @return the value of chapter.cid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.cid
     *
     * @param cid the value for chapter.cid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.ctitle
     *
     * @return the value of chapter.ctitle
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getCtitle() {
        return ctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.ctitle
     *
     * @param ctitle the value for chapter.ctitle
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setCtitle(String ctitle) {
        this.ctitle = ctitle == null ? null : ctitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.cbody
     *
     * @return the value of chapter.cbody
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getCbody() {
        return cbody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.cbody
     *
     * @param cbody the value for chapter.cbody
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setCbody(String cbody) {
        this.cbody = cbody == null ? null : cbody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.ctime
     *
     * @return the value of chapter.ctime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.ctime
     *
     * @param ctime the value for chapter.ctime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", ctitle=").append(ctitle);
        sb.append(", cbody=").append(cbody);
        sb.append(", ctime=").append(ctime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}