package com.gm.gmreader.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatvoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public ChatvoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChidIsNull() {
            addCriterion("chid is null");
            return (Criteria) this;
        }

        public Criteria andChidIsNotNull() {
            addCriterion("chid is not null");
            return (Criteria) this;
        }

        public Criteria andChidEqualTo(Integer value) {
            addCriterion("chid =", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotEqualTo(Integer value) {
            addCriterion("chid <>", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidGreaterThan(Integer value) {
            addCriterion("chid >", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidGreaterThanOrEqualTo(Integer value) {
            addCriterion("chid >=", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidLessThan(Integer value) {
            addCriterion("chid <", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidLessThanOrEqualTo(Integer value) {
            addCriterion("chid <=", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidIn(List<Integer> values) {
            addCriterion("chid in", values, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotIn(List<Integer> values) {
            addCriterion("chid not in", values, "chid");
            return (Criteria) this;
        }

        public Criteria andChidBetween(Integer value1, Integer value2) {
            addCriterion("chid between", value1, value2, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotBetween(Integer value1, Integer value2) {
            addCriterion("chid not between", value1, value2, "chid");
            return (Criteria) this;
        }

        public Criteria andFromidIsNull() {
            addCriterion("fromid is null");
            return (Criteria) this;
        }

        public Criteria andFromidIsNotNull() {
            addCriterion("fromid is not null");
            return (Criteria) this;
        }

        public Criteria andFromidEqualTo(Integer value) {
            addCriterion("fromid =", value, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidNotEqualTo(Integer value) {
            addCriterion("fromid <>", value, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidGreaterThan(Integer value) {
            addCriterion("fromid >", value, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidGreaterThanOrEqualTo(Integer value) {
            addCriterion("fromid >=", value, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidLessThan(Integer value) {
            addCriterion("fromid <", value, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidLessThanOrEqualTo(Integer value) {
            addCriterion("fromid <=", value, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidIn(List<Integer> values) {
            addCriterion("fromid in", values, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidNotIn(List<Integer> values) {
            addCriterion("fromid not in", values, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidBetween(Integer value1, Integer value2) {
            addCriterion("fromid between", value1, value2, "fromid");
            return (Criteria) this;
        }

        public Criteria andFromidNotBetween(Integer value1, Integer value2) {
            addCriterion("fromid not between", value1, value2, "fromid");
            return (Criteria) this;
        }

        public Criteria andToidIsNull() {
            addCriterion("toid is null");
            return (Criteria) this;
        }

        public Criteria andToidIsNotNull() {
            addCriterion("toid is not null");
            return (Criteria) this;
        }

        public Criteria andToidEqualTo(Integer value) {
            addCriterion("toid =", value, "toid");
            return (Criteria) this;
        }

        public Criteria andToidNotEqualTo(Integer value) {
            addCriterion("toid <>", value, "toid");
            return (Criteria) this;
        }

        public Criteria andToidGreaterThan(Integer value) {
            addCriterion("toid >", value, "toid");
            return (Criteria) this;
        }

        public Criteria andToidGreaterThanOrEqualTo(Integer value) {
            addCriterion("toid >=", value, "toid");
            return (Criteria) this;
        }

        public Criteria andToidLessThan(Integer value) {
            addCriterion("toid <", value, "toid");
            return (Criteria) this;
        }

        public Criteria andToidLessThanOrEqualTo(Integer value) {
            addCriterion("toid <=", value, "toid");
            return (Criteria) this;
        }

        public Criteria andToidIn(List<Integer> values) {
            addCriterion("toid in", values, "toid");
            return (Criteria) this;
        }

        public Criteria andToidNotIn(List<Integer> values) {
            addCriterion("toid not in", values, "toid");
            return (Criteria) this;
        }

        public Criteria andToidBetween(Integer value1, Integer value2) {
            addCriterion("toid between", value1, value2, "toid");
            return (Criteria) this;
        }

        public Criteria andToidNotBetween(Integer value1, Integer value2) {
            addCriterion("toid not between", value1, value2, "toid");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andFromnameIsNull() {
            addCriterion("fromname is null");
            return (Criteria) this;
        }

        public Criteria andFromnameIsNotNull() {
            addCriterion("fromname is not null");
            return (Criteria) this;
        }

        public Criteria andFromnameEqualTo(String value) {
            addCriterion("fromname =", value, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameNotEqualTo(String value) {
            addCriterion("fromname <>", value, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameGreaterThan(String value) {
            addCriterion("fromname >", value, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameGreaterThanOrEqualTo(String value) {
            addCriterion("fromname >=", value, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameLessThan(String value) {
            addCriterion("fromname <", value, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameLessThanOrEqualTo(String value) {
            addCriterion("fromname <=", value, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameLike(String value) {
            addCriterion("fromname like", value, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameNotLike(String value) {
            addCriterion("fromname not like", value, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameIn(List<String> values) {
            addCriterion("fromname in", values, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameNotIn(List<String> values) {
            addCriterion("fromname not in", values, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameBetween(String value1, String value2) {
            addCriterion("fromname between", value1, value2, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromnameNotBetween(String value1, String value2) {
            addCriterion("fromname not between", value1, value2, "fromname");
            return (Criteria) this;
        }

        public Criteria andFromimgIsNull() {
            addCriterion("fromimg is null");
            return (Criteria) this;
        }

        public Criteria andFromimgIsNotNull() {
            addCriterion("fromimg is not null");
            return (Criteria) this;
        }

        public Criteria andFromimgEqualTo(String value) {
            addCriterion("fromimg =", value, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgNotEqualTo(String value) {
            addCriterion("fromimg <>", value, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgGreaterThan(String value) {
            addCriterion("fromimg >", value, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgGreaterThanOrEqualTo(String value) {
            addCriterion("fromimg >=", value, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgLessThan(String value) {
            addCriterion("fromimg <", value, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgLessThanOrEqualTo(String value) {
            addCriterion("fromimg <=", value, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgLike(String value) {
            addCriterion("fromimg like", value, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgNotLike(String value) {
            addCriterion("fromimg not like", value, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgIn(List<String> values) {
            addCriterion("fromimg in", values, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgNotIn(List<String> values) {
            addCriterion("fromimg not in", values, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgBetween(String value1, String value2) {
            addCriterion("fromimg between", value1, value2, "fromimg");
            return (Criteria) this;
        }

        public Criteria andFromimgNotBetween(String value1, String value2) {
            addCriterion("fromimg not between", value1, value2, "fromimg");
            return (Criteria) this;
        }

        public Criteria andTonameIsNull() {
            addCriterion("toname is null");
            return (Criteria) this;
        }

        public Criteria andTonameIsNotNull() {
            addCriterion("toname is not null");
            return (Criteria) this;
        }

        public Criteria andTonameEqualTo(String value) {
            addCriterion("toname =", value, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameNotEqualTo(String value) {
            addCriterion("toname <>", value, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameGreaterThan(String value) {
            addCriterion("toname >", value, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameGreaterThanOrEqualTo(String value) {
            addCriterion("toname >=", value, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameLessThan(String value) {
            addCriterion("toname <", value, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameLessThanOrEqualTo(String value) {
            addCriterion("toname <=", value, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameLike(String value) {
            addCriterion("toname like", value, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameNotLike(String value) {
            addCriterion("toname not like", value, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameIn(List<String> values) {
            addCriterion("toname in", values, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameNotIn(List<String> values) {
            addCriterion("toname not in", values, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameBetween(String value1, String value2) {
            addCriterion("toname between", value1, value2, "toname");
            return (Criteria) this;
        }

        public Criteria andTonameNotBetween(String value1, String value2) {
            addCriterion("toname not between", value1, value2, "toname");
            return (Criteria) this;
        }

        public Criteria andToimgIsNull() {
            addCriterion("toimg is null");
            return (Criteria) this;
        }

        public Criteria andToimgIsNotNull() {
            addCriterion("toimg is not null");
            return (Criteria) this;
        }

        public Criteria andToimgEqualTo(String value) {
            addCriterion("toimg =", value, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgNotEqualTo(String value) {
            addCriterion("toimg <>", value, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgGreaterThan(String value) {
            addCriterion("toimg >", value, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgGreaterThanOrEqualTo(String value) {
            addCriterion("toimg >=", value, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgLessThan(String value) {
            addCriterion("toimg <", value, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgLessThanOrEqualTo(String value) {
            addCriterion("toimg <=", value, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgLike(String value) {
            addCriterion("toimg like", value, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgNotLike(String value) {
            addCriterion("toimg not like", value, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgIn(List<String> values) {
            addCriterion("toimg in", values, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgNotIn(List<String> values) {
            addCriterion("toimg not in", values, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgBetween(String value1, String value2) {
            addCriterion("toimg between", value1, value2, "toimg");
            return (Criteria) this;
        }

        public Criteria andToimgNotBetween(String value1, String value2) {
            addCriterion("toimg not between", value1, value2, "toimg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chatvo
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 22 18:13:53 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}