package com.gm.gmreader.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.io.Serializable;
import java.util.Date;

public class Chatvo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.chid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private Integer chid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.fromid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private Integer fromid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.toid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private Integer toid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.content
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.time
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    @JSONField(format="yyyy/MM/dd hh:mm:ss")
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.fromname
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private String fromname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.fromimg
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private String fromimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.toname
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private String toname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatvo.toimg
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private String toimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.chid
     *
     * @return the value of chatvo.chid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Integer getChid() {
        return chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.chid
     *
     * @param chid the value for chatvo.chid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setChid(Integer chid) {
        this.chid = chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.fromid
     *
     * @return the value of chatvo.fromid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Integer getFromid() {
        return fromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.fromid
     *
     * @param fromid the value for chatvo.fromid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setFromid(Integer fromid) {
        this.fromid = fromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.toid
     *
     * @return the value of chatvo.toid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Integer getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.toid
     *
     * @param toid the value for chatvo.toid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setToid(Integer toid) {
        this.toid = toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.content
     *
     * @return the value of chatvo.content
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.content
     *
     * @param content the value for chatvo.content
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.time
     *
     * @return the value of chatvo.time
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.time
     *
     * @param time the value for chatvo.time
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.fromname
     *
     * @return the value of chatvo.fromname
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public String getFromname() {
        return fromname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.fromname
     *
     * @param fromname the value for chatvo.fromname
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setFromname(String fromname) {
        this.fromname = fromname == null ? null : fromname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.fromimg
     *
     * @return the value of chatvo.fromimg
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public String getFromimg() {
        return fromimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.fromimg
     *
     * @param fromimg the value for chatvo.fromimg
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setFromimg(String fromimg) {
        this.fromimg = fromimg == null ? null : fromimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.toname
     *
     * @return the value of chatvo.toname
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public String getToname() {
        return toname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.toname
     *
     * @param toname the value for chatvo.toname
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setToname(String toname) {
        this.toname = toname == null ? null : toname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatvo.toimg
     *
     * @return the value of chatvo.toimg
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public String getToimg() {
        return toimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatvo.toimg
     *
     * @param toimg the value for chatvo.toimg
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setToimg(String toimg) {
        this.toimg = toimg == null ? null : toimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatvo
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chid=").append(chid);
        sb.append(", fromid=").append(fromid);
        sb.append(", toid=").append(toid);
        sb.append(", content=").append(content);
        sb.append(", time=").append(time);
        sb.append(", fromname=").append(fromname);
        sb.append(", fromimg=").append(fromimg);
        sb.append(", toname=").append(toname);
        sb.append(", toimg=").append(toimg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}