package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Chat implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.chid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private Integer chid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.fromid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private Integer fromid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.toid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private Integer toid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.content
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.time
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.chid
     *
     * @return the value of chat.chid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Integer getChid() {
        return chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.chid
     *
     * @param chid the value for chat.chid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setChid(Integer chid) {
        this.chid = chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.fromid
     *
     * @return the value of chat.fromid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Integer getFromid() {
        return fromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.fromid
     *
     * @param fromid the value for chat.fromid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setFromid(Integer fromid) {
        this.fromid = fromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.toid
     *
     * @return the value of chat.toid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Integer getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.toid
     *
     * @param toid the value for chat.toid
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setToid(Integer toid) {
        this.toid = toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.content
     *
     * @return the value of chat.content
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.content
     *
     * @param content the value for chat.content
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.time
     *
     * @return the value of chat.time
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.time
     *
     * @param time the value for chat.time
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Thu Apr 22 18:13:53 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chid=").append(chid);
        sb.append(", fromid=").append(fromid);
        sb.append(", toid=").append(toid);
        sb.append(", content=").append(content);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}