package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Loginlog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.lid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.rid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.rname
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String rname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.rip
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String rip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.time
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginlog.role
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.lid
     *
     * @return the value of loginlog.lid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.lid
     *
     * @param lid the value for loginlog.lid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.rid
     *
     * @return the value of loginlog.rid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.rid
     *
     * @param rid the value for loginlog.rid
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.rname
     *
     * @return the value of loginlog.rname
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.rname
     *
     * @param rname the value for loginlog.rname
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.rip
     *
     * @return the value of loginlog.rip
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getRip() {
        return rip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.rip
     *
     * @param rip the value for loginlog.rip
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setRip(String rip) {
        this.rip = rip == null ? null : rip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.time
     *
     * @return the value of loginlog.time
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.time
     *
     * @param time the value for loginlog.time
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginlog.role
     *
     * @return the value of loginlog.role
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginlog.role
     *
     * @param role the value for loginlog.role
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginlog
     *
     * @mbg.generated Sat Apr 10 17:17:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lid=").append(lid);
        sb.append(", rid=").append(rid);
        sb.append(", rname=").append(rname);
        sb.append(", rip=").append(rip);
        sb.append(", time=").append(time);
        sb.append(", role=").append(role);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}