package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Readerbranchvo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readerbranchvo.rid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readerbranchvo.rname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String rname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readerbranchvo.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readerbranchvo.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readerbranchvo.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bintro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readerbranchvo.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Date btime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readerbranchvo.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String bhimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table readerbranchvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readerbranchvo.rid
     *
     * @return the value of readerbranchvo.rid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readerbranchvo.rid
     *
     * @param rid the value for readerbranchvo.rid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readerbranchvo.rname
     *
     * @return the value of readerbranchvo.rname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readerbranchvo.rname
     *
     * @param rname the value for readerbranchvo.rname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readerbranchvo.bid
     *
     * @return the value of readerbranchvo.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readerbranchvo.bid
     *
     * @param bid the value for readerbranchvo.bid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readerbranchvo.bname
     *
     * @return the value of readerbranchvo.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readerbranchvo.bname
     *
     * @param bname the value for readerbranchvo.bname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readerbranchvo.bintro
     *
     * @return the value of readerbranchvo.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBintro() {
        return bintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readerbranchvo.bintro
     *
     * @param bintro the value for readerbranchvo.bintro
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBintro(String bintro) {
        this.bintro = bintro == null ? null : bintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readerbranchvo.btime
     *
     * @return the value of readerbranchvo.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Date getBtime() {
        return btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readerbranchvo.btime
     *
     * @param btime the value for readerbranchvo.btime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBtime(Date btime) {
        this.btime = btime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readerbranchvo.bhimg
     *
     * @return the value of readerbranchvo.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getBhimg() {
        return bhimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readerbranchvo.bhimg
     *
     * @param bhimg the value for readerbranchvo.bhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setBhimg(String bhimg) {
        this.bhimg = bhimg == null ? null : bhimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readerbranchvo
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", rname=").append(rname);
        sb.append(", bid=").append(bid);
        sb.append(", bname=").append(bname);
        sb.append(", bintro=").append(bintro);
        sb.append(", btime=").append(btime);
        sb.append(", bhimg=").append(bhimg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}