package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Reader implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.rid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.rname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String rname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.rpwd
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String rpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.rmail
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String rmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.rtime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Date rtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.rhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String rhimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.rstate
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private String rstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reader
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.rid
     *
     * @return the value of reader.rid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.rid
     *
     * @param rid the value for reader.rid
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.rname
     *
     * @return the value of reader.rname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.rname
     *
     * @param rname the value for reader.rname
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.rpwd
     *
     * @return the value of reader.rpwd
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getRpwd() {
        return rpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.rpwd
     *
     * @param rpwd the value for reader.rpwd
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRpwd(String rpwd) {
        this.rpwd = rpwd == null ? null : rpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.rmail
     *
     * @return the value of reader.rmail
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getRmail() {
        return rmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.rmail
     *
     * @param rmail the value for reader.rmail
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRmail(String rmail) {
        this.rmail = rmail == null ? null : rmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.rtime
     *
     * @return the value of reader.rtime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Date getRtime() {
        return rtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.rtime
     *
     * @param rtime the value for reader.rtime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRtime(Date rtime) {
        this.rtime = rtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.rhimg
     *
     * @return the value of reader.rhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getRhimg() {
        return rhimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.rhimg
     *
     * @param rhimg the value for reader.rhimg
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRhimg(String rhimg) {
        this.rhimg = rhimg == null ? null : rhimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.rstate
     *
     * @return the value of reader.rstate
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public String getRstate() {
        return rstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.rstate
     *
     * @param rstate the value for reader.rstate
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setRstate(String rstate) {
        this.rstate = rstate == null ? null : rstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", rname=").append(rname);
        sb.append(", rpwd=").append(rpwd);
        sb.append(", rmail=").append(rmail);
        sb.append(", rtime=").append(rtime);
        sb.append(", rhimg=").append(rhimg);
        sb.append(", rstate=").append(rstate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}