package com.gm.gmreader.model;

import java.io.Serializable;
import java.util.Date;

public class Thumb extends ThumbKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.theva
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Boolean theva;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.thtime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private Date thtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thumb
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.theva
     *
     * @return the value of thumb.theva
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Boolean getTheva() {
        return theva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.theva
     *
     * @param theva the value for thumb.theva
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setTheva(Boolean theva) {
        this.theva = theva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.thtime
     *
     * @return the value of thumb.thtime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public Date getThtime() {
        return thtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.thtime
     *
     * @param thtime the value for thumb.thtime
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    public void setThtime(Date thtime) {
        this.thtime = thtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb
     *
     * @mbg.generated Thu Apr 08 17:05:12 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", theva=").append(theva);
        sb.append(", thtime=").append(thtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}